"use client";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { LockKeyhole, ShieldCheck } from "lucide-react";
import { apiRequest } from "@/lib/auth";
import { PageHeading } from "@/components/page-heading";
import { Failure, Loading } from "@/components/live-states";

type Scope = { actions: string[]; resourceClasses: string[]; recordIds?: string[] };
type AccessRequest = { id: string; status: string; expiresAt: string; requestedScopeJson: { scope: Scope; purpose: string }; requester: { displayName: string; providerType: string; verificationStatus: string } };
type Grant = { id: string; status: string; scope: Scope; startsAt: string; expiresAt: string; revokedAt?: string; stellarTxHash?: string };

export function AccessManager() {
  const client = useQueryClient(); const requests = useQuery({ queryKey: ["access-requests"], queryFn: () => apiRequest<AccessRequest[]>("/patients/me/access-requests") }); const grants = useQuery({ queryKey: ["consents"], queryFn: () => apiRequest<Grant[]>("/patients/me/consents") });
  const mutate = useMutation({ mutationFn: ({ path, body }: { path: string; body?: unknown }) => apiRequest(path, { method: "POST", ...(body ? { body: JSON.stringify(body) } : {}) }), onSuccess: async () => { await Promise.all([client.invalidateQueries({ queryKey: ["access-requests"] }), client.invalidateQueries({ queryKey: ["consents"] })]); } });
  if (requests.isPending || grants.isPending) return <Loading />; const error = requests.error ?? grants.error; if (error) return <Failure error={error} />;
  return <><PageHeading eyebrow="YOUR PERMISSION, YOUR BOUNDARIES" title="Access and sharing." description="Approve only the requested scope and expiry. Revocation blocks future API access immediately." /><section className="panel access-panel"><div className="panel-heading"><div><h2>Access requests</h2><p>Only verified clinicians with a current MFA assertion can submit requests.</p></div></div>{requests.data?.filter((item) => item.status === "PENDING").length ? requests.data.filter((item) => item.status === "PENDING").map((request) => <article key={request.id}><div className="provider-row"><span className="avatar">{request.requester.displayName.slice(0, 2).toUpperCase()}</span><div><h3>{request.requester.displayName}</h3><p>{request.requester.providerType} · {request.requester.verificationStatus}</p></div><span className="status-pill pending">Pending</span></div><p className="request-reason">{request.requestedScopeJson.purpose}</p><div className="consent-form"><fieldset><legend>Requested actions</legend>{request.requestedScopeJson.scope.actions.map((action) => <span className="checkbox-row" key={action}><ShieldCheck size={15} />{action}</span>)}</fieldset><fieldset><legend>Resource scope</legend>{request.requestedScopeJson.scope.resourceClasses.map((scope) => <span className="checkbox-row" key={scope}><LockKeyhole size={15} />{scope}</span>)}</fieldset></div><div className="access-actions"><button className="button" onClick={() => mutate.mutate({ path: `/patients/me/access-requests/${request.id}/approve`, body: { scope: request.requestedScopeJson.scope, expiresAt: request.expiresAt } })}>Approve exact request</button><button className="button button-outline" onClick={() => mutate.mutate({ path: `/patients/me/access-requests/${request.id}/reject` })}>Reject</button></div></article>) : <div className="empty-state"><ShieldCheck /><h2>No pending requests</h2><p>New verified clinician requests will appear here.</p></div>}</section>
    <section className="panel access-panel"><div className="panel-heading"><div><h2>Consent grants</h2><p>On-chain status and expiry are visible for every grant.</p></div></div>{grants.data?.length ? grants.data.map((grant) => <div className="grant-row" key={grant.id}><div><h3>{grant.scope.resourceClasses.join(" · ")}</h3><p>{grant.scope.actions.join(" · ")}</p><small>Expires {new Date(grant.expiresAt).toLocaleString()}</small></div><span className={`status-pill ${grant.status === "ACTIVE" ? "" : "pending"}`}>{grant.status.replaceAll("_", " ")}</span>{grant.status !== "REVOKED" && <button className="danger-button" onClick={() => mutate.mutate({ path: `/patients/me/consents/${grant.id}/revoke` })}>Revoke</button>}</div>) : <div className="empty-state"><LockKeyhole /><p>No consent grants.</p></div>}</section>{mutate.error && <p className="error-message" role="alert">{mutate.error.message}</p>}</>;
}
