"use client";
import Link from "next/link";
import { useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Check, FileText } from "lucide-react";
import { apiRequest } from "@/lib/auth";
import type { TimelineEvent } from "@/types/api";
import { PageHeading } from "@/components/page-heading";
import { Failure, Loading } from "@/components/live-states";

export function TimelineView() {
  const client = useQueryClient(); const [editing, setEditing] = useState<string | null>(null); const [reason, setReason] = useState(""); const [display, setDisplay] = useState("");
  const query = useQuery({ queryKey: ["timeline", "me"], queryFn: () => apiRequest<TimelineEvent[]>("/patients/me/timeline") });
  const update = useMutation({ mutationFn: ({ id, status }: { id: string; status: "ACCEPTED" | "CORRECTED" | "REJECTED" }) => apiRequest(`/patients/me/events/${id}`, { method: "PATCH", body: JSON.stringify({ reason: reason || (status === "ACCEPTED" ? "Patient reviewed extraction" : "Patient correction"), fields: display ? { display } : {}, reviewStatus: status }) }), onSuccess: async () => { setEditing(null); setReason(""); setDisplay(""); await client.invalidateQueries({ queryKey: ["timeline", "me"] }); } });
  if (query.isPending) return <Loading />; if (query.error) return <Failure error={query.error} />;
  return <><PageHeading eyebrow="EVIDENCE-BACKED HISTORY" title="Your health timeline." description="Pending extractions require review. Corrections never alter the encrypted original or its hash." /><div className="full-timeline">{query.data.length === 0 ? <section className="panel empty-state"><FileText /><h2>No extracted events yet</h2><p>Upload a record and wait for the ingestion worker.</p></section> : query.data.map((event) => <article className="timeline-entry" id={`event-${event.id}`} key={event.id}><div className="timeline-date"><strong>{new Date(event.occurredAt).toLocaleDateString(undefined, { day: "2-digit", month: "short" })}</strong><span>{new Date(event.occurredAt).getFullYear()}</span></div><span className="timeline-node" /><div className="timeline-entry-card"><span className="eyebrow">{event.eventType.replaceAll("_", " ")} · {event.selfReported ? "SELF-REPORTED" : event.sourceKind.toUpperCase()}</span><h2>{event.interpretation.display ?? "Structured clinical event"}</h2><p>{event.certainty} · {event.reviewStatus.replaceAll("_", " ")}</p><div className="timeline-entry-bottom">{event.citations.map((citation) => <Link key={citation.recordVersionId} href={`/records/${citation.recordId}`}>Source page {citation.page ?? 1}</Link>)}</div>{event.reviewStatus === "PENDING_REVIEW" && <div className="access-actions"><button className="button" onClick={() => update.mutate({ id: event.id, status: "ACCEPTED" })}><Check size={15} /> Accept</button><button className="button button-outline" onClick={() => { setEditing(event.id); setDisplay(event.interpretation.display ?? ""); }}>Correct</button><button className="danger-button" onClick={() => update.mutate({ id: event.id, status: "REJECTED" })}>Reject</button></div>}{editing === event.id && <div className="review-panel"><label className="form-field">Corrected interpretation<textarea value={display} onChange={(e) => setDisplay(e.target.value)} /></label><label className="form-field">Reason<textarea value={reason} onChange={(e) => setReason(e.target.value)} /></label><button className="button" disabled={!reason.trim() || !display.trim()} onClick={() => update.mutate({ id: event.id, status: "CORRECTED" })}>Save correction</button></div>}</div></article>)}</div>{update.error && <p className="error-message" role="alert">{update.error.message}</p>}</>;
}
